### ISSUE TITLE
Remove mrt:jquery-ui?

### ISSUE THREAD

**Issue by MisterAbc** [rzymek/meteor-fullcalendar#10]
Fullcalendar no longer relies on jquery-ui as of this release: https://github.com/arshaw/fullcalendar/releases/tag/v2.1.0

mrt:jquery-ui is several versions behind since it's no longer supported, and have been causing me version conflict errors.

**Comment by rzymek** [comment]
Removed dependency on mrt:jquery-ui and updated to 2.3.1.
