### ISSUE TITLE
The mtr:jquery-ui package is still being installed

### ISSUE THREAD

**Issue by veered** [rzymek/meteor-fullcalendar#11]
I think that you may have to remove it from the .versions file.

**Comment by veered** [comment]
And versions.json

**Comment by rzymek** [comment]
The problem was, that the version 2.3.1 wasn't actually published. I did that just now.
Also `.versions` is updated now, and `versions.json` is removed as it's no longer needed (was used by `mrt`).

**Comment by veered** [comment]
Awesome, thanks for the quick response!
