### ISSUE TITLE
how to add and show task on the calendar?

### ISSUE THREAD

**Issue by thearabbit** [rzymek/meteor-fullcalendar#12]
I am a new for this package.
I would to add/show or remove task on calendar  with due date.
And then example it can alert message before 1 hour of due date.
Please help me.

**Comment by efealatan** [comment]
have you solved this?

**Comment by rzymek** [comment]
Triggering code on due date is out of the scope of fullcalendar. 
You could implement it in meteor using combination of `Collection.observe` and `Meteor.setTimeout`
