### ISSUE TITLE
how to update event info by using eventClick()?

### ISSUE THREAD

**Issue by thearabbit** [rzymek/meteor-fullcalendar#15]
I want to update the event info (db) by using "eventClick", but don't know the collection id
```js
eventClick: function(event, element) {
//
 },
```

**Comment by yozhong** [comment]
How can I trigger eventClick callback function?

**Comment by rzymek** [comment]
You need to pass your eventClick function to the fullcalendar template:

    {{> fullcalendar
        height="100%"
        events=events
        ...
        eventClick=myEventClick
    }}
and then have your template helper return the eventClick handler:

    Template.yourTemplateWithCalendar.helpers({     
        myEventClick: function() {
            return function(calEvent, jsEvent, view) {
                alert("Event clicked: "+calEvent.title);
            }
        }
    });

Consult the [example project](https://github.com/rzymek/meteor-fullcalendar/tree/master/example) for details.
