### ISSUE TITLE
The example doesn't work

### ISSUE THREAD

**Issue by tuxtlequino** [rzymek/meteor-fullcalendar#16]
Although there is an example folder provided, the example files does not work. Other than showing a very simple calendar, the example is not adding any event to the database nor showing any event in a database. Since I am new to this, I really couldn't get it to work without a point of reference.

**Comment by yumikohey** [comment]
I can't run the example either.

**Comment by rzymek** [comment]
I've updated the example. Now there are buttons. that add and remove an event today.

@yumikohey What do you mean? Are you getting some errors? I need something to work with.
