### ISSUE TITLE
Unable to change event colors?

### ISSUE THREAD

**Issue by JustinWestphal** [rzymek/meteor-fullcalendar#17]
Is there something in the package's css that's overriding event background and border colors? Can't seem to set them to what I want no matter what I do. I see other fullcalendar repos seem to have the colors set to the default blue in the packaged css, is this one the same? If so, can we get that rule taken out so we can customize event colors?

**Comment by rzymek** [comment]
No. There's no special css in this package. Only the standard css that
comes in fullcalendar's distribution.
