### ISSUE TITLE
Update fullcalendar

### ISSUE THREAD

**Issue by maksimkurb** [rzymek/meteor-fullcalendar#18]
Hi, update fullcalendar to latest version, please

**Comment by s7dhansh** [comment]
+1
It is behaving badly with the latest momentjs :(

**Comment by maksimkurb** [comment]
@s7dhansh I am too inpatient, so I forked this repo and updated fullcalendar with momentjs to latest versions.
You can install it like this: `meteor add maksimkurb:fullcalendar`

**Comment by s7dhansh** [comment]
@maksimkurb Thanks. why don't you also create a PR so that @rzymek can merge it directly? :)

**Comment by maksimkurb** [comment]
@s7dhansh cos I changed `package.js` file (`rzymek:fullcalendar --> maksimkurb:fullcalendar`), so I was able to upload this package to Atmosphere.js repo

@rzymek can just run `update.sh` and commit update to github.

**Comment by rzymek** [comment]
Version 2.4.0 published

**Comment by s7dhansh** [comment]
Please update momentjs as well :)
