### ISSUE TITLE
Please update momentjs

### ISSUE THREAD

**Issue by s7dhansh** [rzymek/meteor-fullcalendar#20]

**Comment by rzymek** [comment]
Nothing holds you back against using the momentjs version you want.
The version you add explicitly takes precedence over the ones in dependencies:

    meteor create test
    cd test
    meteor add rzymek:fullcalendar
    grep moment .meteor/versions
        momentjs:moment@2.8.4
    meteor  add momentjs:moment@2.10.6
    grep moment .meteor/versions
        momentjs:moment@2.10.6
