### ISSUE TITLE
Not able to output any events at all?

### ISSUE THREAD

**Issue by andregoldstein** [rzymek/meteor-fullcalendar#22]
Hi there, I've tried using this package to output events and no matter which format I try and use I can't seem to output any events at all.

I've tried using a basic array of objects as well as using a function. You wouldn't happen to have a basic example for a basic Meteor collection would you?

Thanks!

**Comment by rzymek** [comment]
There's such an example here in the repo: https://github.com/rzymek/meteor-fullcalendar/tree/master/example

**Comment by andregoldstein** [comment]
Many thanks @rzymek that's great I'll check that out.

Out of interest should I still be able to use the relatively simple examples from the FullCalendar docs from within a simple `rendered` call? 

For example:

```
$('#calendar').fullCalendar({
    events: [
        {
            title  : 'event1',
            start  : '2010-01-01'
        },
        {
            title  : 'event2',
            start  : '2010-01-05',
            end    : '2010-01-07'
        },
        {
            title  : 'event3',
            start  : '2010-01-09T12:30:00',
            allDay : false // will make the time show
        }
    ]
});
```
I can't seem to get any click events working either. Perhaps I'm missing something.

**Comment by dpatte** [comment]
I assume you mean onRendered?

**Comment by andregoldstein** [comment]
Yes @dpatte thanks, I've been using simple examples from their docs such as (in CS):

```
Template.adminLessons.rendered = ->
  $('#calendar').fullCalendar dayClick: (date, jsEvent, view) ->
    alert 'Clicked on: ' + date.format()
    alert 'Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY
    alert 'Current view: ' + view.name
    $(this).css 'background-color', 'red'
```

**Comment by dpatte** [comment]
rendered() is no long correct. the function is onRendered()

**Comment by andregoldstein** [comment]
Bizarre, `onRendered` doesn't work for me at all and `rendered` does work as the calendar itself is showing. Just none of the functions are running on it?

**Comment by andregoldstein** [comment]
Edit: Sorry you are right `onRendered` takes a function as an argument so:

`Template.adminLessons.onRendered ->`

That said it doesn't affect my issue. Both render the calendar.

**Comment by dpatte** [comment]
onRendered is now a function that expects a function as a parameter. rendered = , i believe it may clobber any other onRendered or rendered calls defined for that template. What version of Meteor are you running.

**Comment by andregoldstein** [comment]
Thanks, `1.2.1`.

I think this issue is separate though as the calendar shows, just nothing more than that.

**Comment by andregoldstein** [comment]
Thanks anyway, I've managed to get things working nicely using @rzymek example (even if I'm still trying to figure out the code!) :+1:
