### ISSUE TITLE
Possible example where passing options in JS not template?

### ISSUE THREAD

**Issue by andregoldstein** [rzymek/meteor-fullcalendar#23]
Hi there, would it be possible at all to provide a very basic example where the options are passed as a helper and not directly on the html component (as per the example folder)?

You mention it in your docs but I'm having trouble getting any of the options to work (such as header). When I add them directly to the component, things seem to work but some options (such as header) I presume can only be set in JS.

I'm trying to set something like this in my template:

`{{>fullcalendar options=options events=events}}`

but seemingly the events will be picked up but not the options.

Full JS below:

```
Template.adminLessons.helpers({
  options: function() {
    return {
      defaultView: 'agendaWeek',
      header: {
        left: 'prev,next,today',
        center: 'title',
        right: 'agendaWeek,month,agendaDay'
      }
    };
  },
  events: function() {
    var fc;
    fc = $('.mainCalendar');
    return function(start, end, tz, callback) {
      var lessons;
      Meteor.subscribe('lessons', start.toDate(), end.toDate(), function() {
        return fc.fullCalendar('refetchEvents');
      });
      lessons = _.map(Lessons.find().fetch(), function(event) {
        return {
          title: event.title,
          start: event.start,
          end: event.end,
          className: event.type,
          id: event._id
        };
      });
      return callback(lessons);
    };
  },
  onEventClicked: function() {
    return function(calEvent, jsEvent, view) {
      return Router.go('adminLesson', {
        _id: calEvent.id
      });
    };
  },
  onDayClicked: function() {
    return function(date, jsEvent, view) {
      Session.set('addingEvent', true);
      $('input#title').focus();
      Session.set('addingEventClass', 'active');
      Session.set('addingEventDate', moment(date._d).format('YYYY-MM-DD'));
      Session.set('addingEventStartTime', moment(date._d).format('HH:mm'));
      return Session.set('addingEventEndTime', moment(date._d).add(1, 'hours').format('HH:mm'));
    };
  }
});

Template.adminLessons.rendered = function() {
  var fc;
  fc = this.$('.fc');
  return this.autorun(function() {
    Lessons.find();
    return fc.fullCalendar('refetchEvents');
  });
};
```

Would be great if you could see where I'm going wrong, thanks.

**Comment by rzymek** [comment]
I haven't tested it, but this should do the trick:

    Template.adminLessons.helpers({
        options: function () {
            return {
                defaultView: 'agendaWeek',
                header: {
                    left: 'prev,next,today',
                    center: 'title',
                    right: 'agendaWeek,month,agendaDay'
                },
                events: function () {
                    var fc = $('.mainCalendar');
                    return function (start, end, tz, callback) {
                        Meteor.subscribe('lessons', start.toDate(), end.toDate(), function () {
                            fc.fullCalendar('refetchEvents');
                        });
                        var lessons = _.map(Lessons.find().fetch(), function (event) {
                            return {
                                title: event.title,
                                start: event.start,
                                end: event.end,
                                className: event.type,
                                id: event._id
                            };
                        });
                        return callback(lessons);
                    };
                },
                eventClick: function (calEvent, jsEvent, view) {
                    return Router.go('adminLesson', {
                        _id: calEvent.id
                    });
                },
                dayClick: function (date, jsEvent, view) {
                    Session.set('addingEvent', true);
                    $('input#title').focus();
                    Session.set('addingEventClass', 'active');
                    Session.set('addingEventDate', moment(date._d).format('YYYY-MM-DD'));
                    Session.set('addingEventStartTime', moment(date._d).format('HH:mm'));
                    return Session.set('addingEventEndTime', moment(date._d).add(1, 'hours').format('HH:mm'));
                }
            }
        }
    });
    
    Template.adminLessons.rendered = function () {
        var fc = this.$('.fc');
        return this.autorun(function () {
            Lessons.find();
            return fc.fullCalendar('refetchEvents');
        });
    };

With 

    {{>fullcalendar options}}

**Comment by andregoldstein** [comment]
@rzymek Thank you so much for taking the time to reply. That works perfectly. I was sure it must have been possible but was obviously going wrong somewhere! :+1:

**Comment by andregoldstein** [comment]
Actually, sorry, I tell a lie, for some reason the options are being passed but the events are never received from the subscription.

**Comment by andregoldstein** [comment]
@rzymek Is the problem here that we still need to pass in a class or id to the calendar and with just the `options` keyword then we can't do this?

I'm using `babrahams:constellations` and can see that I've not got any current subscription to my `lesson`.

Is it still possible to send the class/id to fullCalendar when declaring `option` on the template?

Thanks again

**Comment by chriskgregory** [comment]
I'm having the same issue. Events are not properly being received. All other fullCalendar packages work, though this is the most updated one and unfortunately doesn't seem to work.

**Comment by rzymek** [comment]
Basically you have two options.
1) `{{> fullcalendar options}}`

    Template.adminLessons.helpers({
        options: function() {
            id: 'calendarId',
            'class': 'calendarClass',
            eventClick: function(calendarEvent, jsEvent, view) { /* ... */ }
        }
    });

2) `{{>fullcalendar id=calId class=calClass eventClick=eventClick}}`

    Template.adminLessons.helpers({
        calId: 'calendarId',
        calClass: 'calendarClass',
        eventClick: function(calendarEvent, jsEvent, view) { /* ... */ }
    });

**Comment by nosizejosh** [comment]
I am having a similar challenge and just realised the return function is never called.
 ` events: function () {
                var fc = $('clndr');
                return function (start, end, tz, callback) {
                    console.log(3);
                    Meteor.subscribe('appointments', start.toDate(), end.toDate(), function () {
                        fc.fullCalendar('refetchEvents');
                    });
                    var lessons = _.map(Appointments.find().fetch(), function (event) {
                        return {
                            title: event.title,
                            start: event.start,
                            end: event.end
//                            ,
//                            className: event.type,
//                            id: event._id
                        };
                    });
                    return callback(lessons);
                };
            },`
please help
