### ISSUE TITLE
Calendar design

### ISSUE THREAD

**Issue by MarcSchwenzner** [rzymek/meteor-fullcalendar#26]
Hello,
i have a question. Is it possible to change the design of the calendar, so it just shows the number of the day as field ? And if it's possible, how can i do it ?
It should look something like this:
![calendar](https://cloud.githubusercontent.com/assets/5930557/12298242/7906f8ac-ba11-11e5-91f0-cb9f86cc7e5f.JPG)

Thanks !

**Comment by rzymek** [comment]
This github project is just for fullcalendar's meteor integration. Try the [general fullcalendar's forums](http://fullcalendar.io/support/) for your answer.
