### ISSUE TITLE
Can I set header options in the meteor template, if so what's the syntax?

### ISSUE THREAD

**Issue by jsbono** [rzymek/meteor-fullcalendar#30]
{{> fullcalendar
                 class="mainCalendar"
                  id="myCalendar"
                  defaultView='month'
                  height="100%"
                 events=events
                 eventClick=onEventClicked
                 eventDrop=onEventDrop
                 eventResize=onEventResize
                 dayClick=onDayClick
                 editable=true
               **  header=[?]**

}}

Note, it appears that if I set the options in the template, I can't also set them on rendered which is where I have the below code which seems to be overwritten or ignored. thanks!

$('#myCalendar').fullCalendar({
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'month,agendaWeek,agendaDay'
    }
  });

**Comment by rzymek** [comment]
You'll have to use a helper method to create the header object:

    Templates.myTemplate.helpers({
        calendarHeader: function() {
            return {
              left: 'prev,next today',
              center: 'title',
              right: 'month,agendaWeek,agendaDay'
            }
        }
    });
And then

    <template name="myTemplate"> 
        
        {{> fullcalendar
          class="mainCalendar"
          id="myCalendar"
          defaultView='month'
          height="100%"
          events=events
          eventClick=onEventClicked
          eventDrop=onEventDrop
          eventResize=onEventResize
          dayClick=onDayClick
          editable=true
          header=calendarHeader          
        }}
      
    </template>

**Comment by jsbono** [comment]
Terrific, thanks!
