### ISSUE TITLE
dayClick callback in options not working

### ISSUE THREAD

**Issue by newbiesunited** [rzymek/meteor-fullcalendar#31]
I have my code in a calendar.js file as follows:

    var calendar = $('#calendar').fullCalendar({
        dayClick: function(date, jsEvent, view){
            var newEvent = {};
            newEvent.start = date._d;
            newEvent.end = date._d;
            newEvent.title = "New Event";
            Meteor.call('saveCalEvent', newEvent);
        }
    });

The server-side method will insert a new Event Object at that date, but it is of little relevance because the code crashes before that line. I repeatedly receive the Uncaught TypeError: m._d.getTime is not a function at moment.js:93 in my console and am unable to continue. I was reading that this might be due to the my moment.js version, it is currently at 2.11.2 and my fullCalendar version is at 2.6.0

Any assistance would be greatly appreciated; the console error is screenshotted below:
![image](https://cloud.githubusercontent.com/assets/12626929/12961767/1874ccee-d07d-11e5-8431-9f0482392ec4.png)

**Comment by rzymek** [comment]
Try changing `newEvent.start` and `.end` to hold pure JS date instead of
moment (using `_d.toDate`)

**Comment by newbiesunited** [comment]
Hi @rzymek thank you for the timely reply, I forgot to include that the ._d in date._d was not there previously, the error persists even when the code went like this:

`var calendar = $('#calendar').fullCalendar({
        dayClick: function(date, jsEvent, view){
            var newEvent = {};
            newEvent.start = date;
            newEvent.end = date;
            newEvent.title = "New Event";
            Meteor.call('saveCalEvent', newEvent);
        }
    });`

**Comment by newbiesunited** [comment]
Hey @rzymek sorry to bother but can I just check back on the status of this issue? I'm sorry to badger but I need to rectify this asap

**Comment by rzymek** [comment]
Still, according to [dayClick docs](http://fullcalendar.io/docs/mouse/dayClick/) the `date` parameter is a `Moment` instance. You can send `Date` objects to the server, not `Moment`. So, as I've said before, you need to convert moment to date:

    var calendar = $('#calendar').fullCalendar({
        dayClick: function(date, jsEvent, view){
            var newEvent = {};
            newEvent.start = date.toDate();
            newEvent.end = date.toDate();
            newEvent.title = "New Event";
            Meteor.call('saveCalEvent', newEvent);
        }
    })

**Comment by newbiesunited** [comment]
Hey @rzymek, how silly of me I did not know that the server is unable to handle moment objects. Thank you so much for your kind help. Much appreciated!

**Comment by newbiesunited** [comment]
Hey @rzymek why is Meteor server side unable to handle moment objects? I tried initialising moment objects via meteor shell and it works just fine. Is it something to do with the incompatibility of the momentjs versions between the server side and the one used by FullCalendar?

**Comment by rzymek** [comment]
It's not that the server side can't handle moment, it can. The problem is with transferring the moment object via DDP from the client to the server (or vice-versa). When you call a Meteor method on the client, all it's parameters need to be serialized to [EJSON](https://docs.meteor.com/#/full/ejson) and it can't handle moment objects out of the box. So to work around this problem I usually pass pure JS Date object between client and server. I think you could make it work with moment using [EJSON.addType(name, factory)](https://docs.meteor.com/#/full/ejson_add_type)

**Comment by osv** [comment]
convert to number should work I think: `newEvent.start = +date` and in server side just do new `new Date(newEvent.start)`

**Comment by rajeshwarpatlolla** [comment]
I also had a similar problem. I found a solution. The below link might help you.
https://discuss.emberjs.com/t/sendaction-from-component-with-fullcalendar/7471/1
