### ISSUE TITLE
update

### ISSUE THREAD

**Issue by nosizejosh** [rzymek/meteor-fullcalendar#32]
Can you please update fullcalendar and also show me how to update locally so I don't have to be coming to you áll the time.

I tried to follow this To update fullcalendar version run ./update.sh but was not sure where to run that command from.
 where can I locate the source files so i replace the calendar.js file with the latest one. I am thinking that will be the easiest way to update. No?

Thanks.

**Comment by rzymek** [comment]
I've published version 2.6.1 to atmosphere. 
In case you can't wait to use a new fullcalendar version in your project, you can update the package locally:

    cd your_meteor_project
    mkdir -p packages
    git clone https://github.com/rzymek/meteor-fullcalendar packages/rzymek:fullcalendar
    ./packages/rzymek:fullcalendar/update.sh

After the desired version gets published just remove the local package:

    rm -r packages/rzymek:fullcalendar
