### ISSUE TITLE
Update to 2.7.2

### ISSUE THREAD

**Issue by dvolland** [rzymek/meteor-fullcalendar#36]
Would be nice to update to 2.7.2, because of https://github.com/fullcalendar/fullcalendar/issues/3152
and the changes listed in https://github.com/fullcalendar/fullcalendar/blob/master/CHANGELOG.md#v272-2016-05-20.

**Comment by miri-am** [comment]
cool. Thanks!

**Comment by dvolland** [comment]
cool. Thanks!
