### ISSUE TITLE
$('.fc').fullCalendar('refetchEvents') is undefined

### ISSUE THREAD

**Issue by ifalldev** [rzymek/meteor-fullcalendar#39]
Hi, i can't refetch events.

I've tried everything to make the calendar reactive, but i noticed that _the function_ `$('.fc').fullCalendar('refetchEvents')` _does not return or does nothing._

The best i could do was this call `$('.fc').fullCalendar('destroy')` before `$('.fc').fullCalendar(events)`.

I need some help with this );

**Comment by rzymek** [comment]
`('.fc').fullCalendar('refetchEvents')` just triggers the refresh of events date. It's supposed to not return anything. It suppose to call the functions defined via 'events' field. Check out https://github.com/rzymek/meteor-fullcalendar/blob/master/example/client/example.js

**Comment by ifalldev** [comment]
Thank you for quick awnser!

I was fallowing this example and the issues here.

The way i came to my conclusion(`fullCalendar('refetchEvents') `have no action) was that _i added data_ to my collection and _tried call_ `$('.fc').fullCalendar('refetchEvents')` from chrome console. Nothing changed on calendar.

I put console.log, for debug propose, on `this.autorun(function() {...})` and after on `.observe()` and after on `observeChanges()`. _All of them worked well_.

**Comment by ifalldev** [comment]
I don't know why but when i tried to change to `fullcalendar:fullcalendar` package everything went fine.

I'm going to do a little test to understand what I was doing wrong later 'cause I have no time now.

As soon as I can, I'll provide more details.

Thank you.
