### ISSUE TITLE
Theme and buttons not loading

### ISSUE THREAD

**Issue by mesosteros** [rzymek/meteor-fullcalendar#4]
I'm trying to import my calendar and yet I just get the blank calendar even if I only add a few basic options.
How do we do this?

I'd also like to know if you're working to get the package with Full Calendar 2.2.3 soon :)

**Comment by tintoverano** [comment]
hi,

thanks for the package

somehow setting the height and contentHeight attributes at init time have no effect, others seem to work like firstDay, defaultView

any ideas what can be wrong?

thanks,

zoltán

**Comment by rzymek** [comment]
Please create a repo that shows the problem, or at least show me some code.

**Comment by tintoverano** [comment]
hi,

I used your example and just added a few lines:

    options: function () {
      return {
        defaultView: 'basicWeek',
        firstDay: '1',
        height: '200'
      }
    }

setting "height" like this has no effect

thanks!!

**Comment by tintoverano** [comment]
sorry, my bad! 

it is ok, found the problem

thanks for your support!

**Comment by rzymek** [comment]
Yeah, you can see in the [fullcalendar docs](http://fullcalendar.io/docs/display/height/) that the height needs to be numerical not a string. This worked:

    options: function () {
      return {
        defaultView: 'basicWeek',
        height: 200
      }
    }

BTW. When you post that you've solved your problem - include your solution!

**Comment by mesosteros** [comment]
I just got back into this. The new version (2.2.6) worked right out of the bag. Thanks for your work :+1:
