### ISSUE TITLE
How to query date and time from new collection?

### ISSUE THREAD

**Issue by mazin933** [rzymek/meteor-fullcalendar#47]
I have collection called `Requests` in my project. One of its attributes is stored as follow : `"requestedDateTime": "August 11, 2017 at 3:27 AM"` 

Is it possible to query the date and time from `Requests` collection to the fullCalendar?

And is there any documentation I can refer to about this package?

**Comment by rzymek** [comment]
Fullcalendar docs:
https://fullcalendar.io/docs/
