### ISSUE TITLE
Error using the events function callback - "Exception from Tracker afterFlush function: boolean is not a function"

### ISSUE THREAD

**Issue by manuelmateus16** [rzymek/meteor-fullcalendar#5]
Hello,

I am using this package and I am experiencing some problems when using the callback from the events function. Here is the code:

events: function(start, end, callback){
                var eventos = Aulas.find().fetch();
                console.log(eventos);
                callback(eventos);
            }

And the error:
![error](https://cloud.githubusercontent.com/assets/4751516/5910647/51b101de-a5b4-11e4-9618-e0646fe3c8a4.png)

Any clue on what is going wrong?

Thanks in advance

**Comment by rzymek** [comment]
First idea: 
The docs for [events as a function](http://fullcalendar.io/docs/event_data/events_function/) say that the third parameter is a `timezone` not a `callback`.
Consider checking it:

    events: function(start, end, callback){
       console.log(arguments);
       ....

Besides this, I'd need a more complete example to help.

**Comment by manuelmateus16** [comment]
That was the problem! I was not considering the timezone argument (was not existent in the earliest fullcalendar version 1). 

Thanks a lot and sorry for the dumb question.
