### ISSUE TITLE
template helpers other than "options" are not called, it seems

### ISSUE THREAD

**Issue by tintoverano** [rzymek/meteor-fullcalendar#6]
hi,

using the latest version like this

````
<template name="weekStripe">
    <div class="container" style="margin-top: 70px;">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    {{> fullcalendar options}}
                </div>
            </div>
        </div>
    </div>
</template>
````

````
  Template.weekStripe.helpers ({
    options: function () {
      return {
        defaultView: 'basicWeek',
        firstDay: 1,
        height: 150
      }
    },

    dayClick: function (date, jsEvent, view) {
      alert('a day has been clicked!');
    }
  });
````

dayClick is not called in my case

am I missing something required?

cheers

**Comment by rzymek** [comment]
I think you it should be like this:

    Template.weekStripe.helpers ({
      options: function () {
        return {
          dayClick: function (date, jsEvent, view) {
            alert('a day has been clicked!');
          },
          defaultView: 'basicWeek',
          firstDay: 1,
          height: 150
        }
      },
    });

**Comment by tintoverano** [comment]
yes, it works like that :)

thanks for the quick support and the package!

**Comment by yuomtheara** [comment]
Why, it have problem with load order?
