### ISSUE TITLE
how to call .fullCalendar( 'rerenderEvents' )

### ISSUE THREAD

**Issue by tintoverano** [rzymek/meteor-fullcalendar#7]
hi,
I'm adding events after the calendar template is created (via the 'events' call back), but the events are only shown when I click on 'next' and not after the 'events' callback...

so I thought using 'rerenderEvents', but how to call it in the client code?

thanks,

tinto

**Comment by rzymek** [comment]
You need to use fullcalendar as a JQuery plugin instead of the `{{> fullcalendar}}` helper.
HTML:

    <template name="calendar">
      <div id="cal"></div>
      
    </template>
JS:

    Template.calendar.rendered = function() {
      this.$('#cal').fullCalendar({ /* options */ });
    }
    Template.calendar.events({
      'click ....': function(e,template) {
        template.$('#cal').fullCalendar('rerenderEvents');
      }
    });

**Comment by tintoverano** [comment]
thanks

I've made the changes and inserted ````$('#cal').fullCalendar('rerenderEvents')```` into another template's helper, but it has no effect on the calendar, there's no error neither

sorry about the trouble I'm learning both Meteor and JQuery

**Comment by tintoverano** [comment]
````refetchEvents```` did the trick

**Comment by thearabbit** [comment]
I try use 
```js
Template.calendar.onRendered(function () {
    Collection.Calendar.find({}).observeChanges({

        added: function (id, fields) {
            console.log('Calendar is added');
            $('#myFullcalendar').fullCalendar('refetchEvents');
        },

        changed: function (id, fields) {
            console.log('Calendar is changed');
            $('#myFullcalendar').fullCalendar('refetchEvents');
        },

        removed: function (id) {
            console.log('Calendar is removed');
            $('#myFullcalendar').fullCalendar('refetchEvents');
        }
    });
});
```
but not work??

**Comment by thearabbit** [comment]
After I change or remove the data, If I click `today btn or pre, next btn`, It is work fine.
Please help me.
