### ISSUE TITLE
How to render events stored in a collection?

### ISSUE THREAD

**Issue by mesosteros** [rzymek/meteor-fullcalendar#8]
How can I render events stored in a collection?
I can find the events but they don't render on the package's calendar (only my google calendar events are rendering).

**Comment by rzymek** [comment]
One option is to supply the events via [`events` function](http://fullcalendar.io/docs/event_data/events_function/).:

    Template.example.helpers({
        options: function() {
            return {
                events: function(start, end, timezone, callback) {
                    callback(Collection.find({start: {$qt:start}}).fetch());
                },
                defaultView: 'basicWeek'
            };
        }
    });
To reactively update events:

    Tracker.autorun(function () {
        $('.fc').fullcalendar('refetchEvents');
    });
  
This is far form optimal, but should give you an idea how to interact.
BTW. I need to extend the `{{>fullcalendar}}` template to allow to assign an `id` or `class` attribute to the `<div>` it generates. This will allow for something more precise than `$('.fc')`

**Comment by mesosteros** [comment]
Yeah those were actually the two things I wanted to know because I had been using the $('.calendar') in my non Meteor code. I think that information about .fc should be on the README.md.
I didn't know I had to get a callback like that in events, I will try it as you described. Thanks for the quick reply.

**Comment by mesosteros** [comment]
I just noticed you have a qt operator in that code. I don't know what that is: I've searched both Meteor and MongoDB's docs and it is giving me an error on my browser when I execute this function except it is in the selector.js file of the package.

**Comment by rzymek** [comment]
I meant [`$gt`](http://docs.mongodb.org/manual/reference/operator/query/gt/#op._S_gt)
Sorry about that.

**Comment by mesosteros** [comment]
Solved one part. All I needed was:

                        events: function(start, end, timezone, callback) {
                          callback(Eventos.find({}).fetch());
                        }

However the events aren't rendering immediately. I need to move to another week or view before they display. Even with the autorun code.

**Comment by mesosteros** [comment]
Ok got back into this (I can insert, update and remove events perfectly now). The issue with the events not rendering immediately is with the Tracker.autorun function you suggested. Once the calendar loads I get the following error in the browser console:

Uncaught TypeError: undefined is not a functioncalendar.js?2b27a22ffe706945b12dc21a78d379493baa25f6:885 (anonymous function)tracker.js:263 Tracker.Computation._computetracker.js:181 Tracker.Computationtracker.js:454 Tracker.autoruncalendar.js?2b27a22ffe706945b12dc21a78d379493baa25f6:884 (anonymous function)calendar.js?2b27a22ffe706945b12dc21a78d379493baa25f6:888 (anonymous function)

I guess this is because when the Tracker runs the calendar options helper has not yet loaded.

**Comment by rzymek** [comment]
>I guess this is because when the Tracker runs the calendar options helper has not yet loaded. 

If that's the case, then register `autorun` inside template's `rendered` callback:

    Template.with_calendar.rendered = function() {
      this.autorun(function(){
        $('.fc').fullcalendar('refetchEvents');
      });
    }

**Comment by mesosteros** [comment]
Hmm... that wasn't it. I have tried in quite a few ways (calendarTemplate.autorun($('.fc').fullcalendar('refetchEvents'); / Inside rendered directly)... Get an error every time with that. But only that first rendering doesn't show events... even with the error If I navigate around my events get fetched. So it really has to do with the autorun.

**Comment by mesosteros** [comment]
Good news... the error was one of those dumb little things... CamelCase... I had fullcalendar instead of fullCalendar. My editor syntax theme made the c look like its uppercase version.

Bad news: I still don't get any events on startup, only when I move between views are they rendered.

**Comment by cmfcmf** [comment]
Hi @rzymek @mesosteros!

I had the same problem and [this](https://github.com/rzymek/meteor-fullcalendar/issues/8#issuecomment-72874807) indeed did the trick. I recommend to add it to the README, because it IMHO is a pretty common usecase.

**Comment by rzymek** [comment]
I've started to update to example to use collections. I've come up with something like this:

    Template.body.helpers({
        events: function () {
            var fc = $('.fc');
            return function (start, end, tz, callback) {
                //subscribe only to specified date range
                Meteor.subscribe('events', start, end, function () {
                    //trigger event rendering when collection is downloaded
                    fc.fullCalendar('refetchEvents');
                });

                //find all, because we've already subscribed to a specific range
                var events = Events.find().map(function (it) {
                    return {
                        title: it.date.toISOString(),
                        start: it.date,
                        allDay: true
                    };
                });
                callback(events);
            };
        }
    });
    Template.body.rendered = function () {
        var fc = this.$('.fc');
        this.autorun(function () {
            //1) trigger event re-rendering when the collection is changed in any way
            //2) find all, because we've already subscribed to a specific range
            Events.find();
            fc.fullCalendar('refetchEvents');
        });
    };

**Comment by cmfcmf** [comment]
Thank you!
>
>

**Comment by lzwaan** [comment]
When i tried to add an event in my mongodb collection, i receive the following message in my browser:
Cannot read property 'toISOString' of undefined

Command:

db.events.insert({
        "allDay": "",
        "title": "Test event",
        "id": "821",
        "end": "2011-06-06 14:00:00",
        "start": "2011-06-06 06:00:00"
    })

What do i wrong in this case?
Is it possible to feed the calendar with a json collection without saving this in a mongo database?

**Comment by ThePanuto** [comment]
@lzwaan in the .html file:

    <template name="events">
        {{> fullcalendar events=myEvents
    </template>

In the .js file

    Template.events.helpers({
         myEvents: function() {
             return [{title: 'foo', start: '2015-04-18'}]
         }
    });

**Comment by Jocoder** [comment]
Is there any update on this issue? I was using @rzymek s example and it works but I am having performance issues because of this function being called constantly due to the reactivity: 

```javascript
Meteor.subscribe('events', start, end, function () {
                //trigger event rendering when collection is downloaded
                fc.fullCalendar('refetchEvents');
            });
```

**Comment by brdtrpp** [comment]
I cannot get the events to render on first show. Any solution to this yet?

**Comment by nubunto** [comment]
@brdtrpp to render on first show, you have to set a hook to `Tracker.autorun`. That worked at my project. E.g.:

    Tracker.autorun(function() {
        $('#myCalendar').fullCalendar('refetchEvents');
    });

Or use the example from @rzymek above:

    Template.body.rendered = function () {
        var fc = this.$('.fc');
        this.autorun(function () {
            //1) trigger event re-rendering when the collection is changed in any way
            //2) find all, because we've already subscribed to a specific range
            Events.find();
            fc.fullCalendar('refetchEvents');
        });
    };
  
@Jocoder performance issues can be mitigated through publishing and subscribing a subset of your collection through Meteor's pub/sub system.
