### ISSUE TITLE
Does this support Google Calendar?

### ISSUE THREAD

**Issue by jamiewilson** [rzymek/meteor-fullcalendar#9]
Does this port work the same way with Google Calendar integration? http://fullcalendar.io/docs/google_calendar/

**Comment by rzymek** [comment]
Haven't tried it, but yes - it should work the same way. You could place `gcal.js` in

    client/lib/compatibility
or wrap it in it's own package (pull request is welcome)

**Comment by jamiewilson** [comment]
Awesome! I'll send you a PR this week.

**Comment by jamiewilson** [comment]
Actually, works great out of the box without moving gcal.js anywhere. Thanks for sharing this. working great for me!
